% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This code is shared under the Creative Commons (CC BY-SA 4.0) license.
% Authorship of this piece of code is credited to Adriel Sosa PhD (email: 
% adriel.sosa@ulpgc.es)
% The code is provided as is, so the author is not responsible for any kind 
% of flaw, inaccuracy or malfunctioning it may contain.
% Copyright (r) CC BY-SA 4.0, 2021 
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function cosmors = new_cosmors( )
%NEW_COSMORS Create a new structure to set a COSMO-RS calculation
%   !!PARAMETERS===========================================================
%   1) .ncomponents   => Number of components in the mixture
%   2) .num_bat_files => Number of .bat files into which distribute
%                        calculations
%   3) .wdir          => Set root working directory with all cosmotherm I/O
%                        files
%   4) .Tgridsz       => Number of ptx conditions for property evaluation
%   5) .dbpath        => Path to .cosmo/.vap files database
%   6) .system        => Name of the n-ary system to be evaluated
%   7) .batch         => .bat filename
%   8) .calc          => Type of calculation identifier (just for tracking,
%                        not mandatory. Default "elv")
%   9) .header1       => COSMO-RS version file and location (Check a ".inp"
%                        file generated by cosmotherm to know how to set it
%   10) .header2      => COSMO-RS general parameters settings. This should
%                        be modified according to each specific task. Check
%                        cosmotherm guide to  see available options. 
%                        (Default: output units in SI)
%   11) .jinstruction => Job instruction to be executed by cosmo. (Default:
%                        Isothermal (temperature in K) VLE calculation with
%                        HE_split option to obtain interactional
%                        contributions to the mixing enthalpy)
%   12) .binstruction => Instructions of .bat files. In general, default
%                        instruction applies for all kinds of COSMO-RS jobs
%   13) .comp         => Pure component name pattern (usually valid for all
%                        kind of calculations)
%   !! ====================================================================

cosmors.ncomponents = 7;
cosmors.num_bat_files = 1;
cosmors.wdir = 'D:/TERMO/TL Matlab/cases/%s/COSMO/';
cosmors.Tgridsz = 1;        % Temperature grid size
cosmors.dbpath = '';
cosmors.system = '';
cosmors.batch = 'run_batch_B0000001.bat';
cosmors.calc = 'elv';

% COSMO-RS script pattern
cosmors.header1 = 'ctd = BP_TZVP_C30_1201.ctd cdir = "C:\Program Files (x86)\COSMOlogic\COSMOthermX12\COSMOthermX\..\COSMOtherm\CTDATA-FILES"  VPfile EHfile LDIR = "C:\Program Files (x86)\COSMOlogic\COSMOthermX12\licensefiles"';
cosmors.header2 = 'wtln unit=si notempty ehfile';
cosmors.jinstruction = 'binary={1 2} tk=%3.1f HE_SPLIT    # Automatic Phase Diagram Calculation';
cosmors.binstruction = 'cosmotherm "%s"\n';
cosmors.comp = 'f = %s fdir="%s/%s" VPfile\n';


cosmors = orderfields(cosmors);

